export interface CountryVisit {
  name: string
}

// Keys are ISO 3166-1 numeric codes exactly as stored in world-atlas countries-110m.json
export const visitedCountries: Record<string, CountryVisit> = {
  '124': { name: 'Canada' },
  '840': { name: 'United States' },
  '724': { name: 'Spain' },
  '292': { name: 'Gibraltar' },
  '484': { name: 'Mexico' },
  '604': { name: 'Peru' },
  '152': { name: 'Chile' },
  '188': { name: 'Costa Rica' },
  '380': { name: 'Italy' },
  '336': { name: 'Vatican City' },
  '756': { name: 'Switzerland' },
  '792': { name: 'Turkey' },
  '300': { name: 'Greece' },
  '191': { name: 'Croatia' },
  '784': { name: 'United Arab Emirates' },
  '710': { name: 'South Africa' },
  '072': { name: 'Botswana' },
  '716': { name: 'Zimbabwe' },
  '894': { name: 'Zambia' },
  '516': { name: 'Namibia' },
  '462': { name: 'Maldives' },
  '458': { name: 'Malaysia' },
  '158': { name: 'Taiwan' },
  '344': { name: 'Hong Kong' },
  '250': { name: 'France' },
  '826': { name: 'United Kingdom' },
  '764': { name: 'Thailand' },
  '704': { name: 'Vietnam' },
  '702': { name: 'Singapore' },
  '360': { name: 'Indonesia' },
  '376': { name: 'Israel' },
  '400': { name: 'Jordan' },
  '246': { name: 'Finland' },
  '233': { name: 'Estonia' },
  '528': { name: 'Netherlands' },
  '643': { name: 'Russia' },
  '752': { name: 'Sweden' },
  '276': { name: 'Germany' },
  '208': { name: 'Denmark' },
  '348': { name: 'Hungary' },
  '620': { name: 'Portugal' },
  '392': { name: 'Japan' },
  '144': { name: 'Sri Lanka' },
  '356': { name: 'India' },
  '032': { name: 'Argentina' },
  '076': { name: 'Brazil' },
  '056': { name: 'Belgium' },
  '442': { name: 'Luxembourg' },
}
