export interface CountryVisit {
  name: string
  description: string
}

// Keys are ISO 3166-1 numeric codes (as strings) matching world-atlas topojson IDs
export const visitedCountries: Record<string, CountryVisit> = {
  '840': { name: 'United States', description: 'Home.' },
  '724': { name: 'Spain', description: 'Gibraltar (2005). Madrid & Southampton cruise stop (2018).' },
  '292': { name: 'Gibraltar', description: 'Visited 2005.' },
  '484': { name: 'Mexico', description: 'Visited 2011.' },
  '604': { name: 'Peru', description: 'Visited 2011.' },
  '152': { name: 'Chile', description: 'Visited 2011.' },
  '188': { name: 'Costa Rica', description: 'Visited 2011.' },
  '380': { name: 'Italy', description: 'Cinque Terre, Pisa, Rome, Tuscany, Como, Venice & Florence (2012). Tuscany & Elba (2018).' },
  '336': { name: 'Vatican City', description: 'Visited 2012.' },
  '756': { name: 'Switzerland', description: 'Visited 2012.' },
  '792': { name: 'Turkey', description: 'Ephesus (2012).' },
  '300': { name: 'Greece', description: 'Athens (2012).' },
  '191': { name: 'Croatia', description: 'Dubrovnik (2012). Split & Brač (2018).' },
  '784': { name: 'United Arab Emirates', description: 'Dubai (2012 & 2019).' },
  '710': { name: 'South Africa', description: 'Johannesburg & Kruger National Park (2012).' },
  '72':  { name: 'Botswana', description: 'Safari (2012).' },
  '716': { name: 'Zimbabwe', description: 'Victoria Falls (2012).' },
  '894': { name: 'Zambia', description: 'Victoria Falls border crossing (2012).' },
  '516': { name: 'Namibia', description: 'Brief stop (2012).' },
  '462': { name: 'Maldives', description: 'Visited 2012.' },
  '458': { name: 'Malaysia', description: 'Kuala Lumpur (2012).' },
  '158': { name: 'Taiwan', description: 'Taipei & Yehliu Park (2012).' },
  '344': { name: 'Hong Kong', description: 'Visited 2012 & 2016.' },
  '250': { name: 'France', description: 'Paris (2014).' },
  '826': { name: 'United Kingdom', description: 'London (2014). Southampton cruise port (2018).' },
  '764': { name: 'Thailand', description: 'Koh Samui & Bangkok (2016). Phuket — Freedom Beach (2019).' },
  '704': { name: 'Vietnam', description: 'Da Nang, Hoi An & Ho Chi Minh City / Saigon (2016).' },
  '702': { name: 'Singapore', description: 'Visited 2016 & 2019.' },
  '360': { name: 'Indonesia', description: 'Telunas (2016).' },
  '376': { name: 'Israel', description: 'March break 2017 & summer 2022.' },
  '400': { name: 'Jordan', description: 'March break 2017.' },
  '246': { name: 'Finland', description: 'Helsinki (2018).' },
  '233': { name: 'Estonia', description: 'Tallinn (2018).' },
  '528': { name: 'Netherlands', description: 'Amsterdam (2018).' },
  '643': { name: 'Russia', description: 'St. Petersburg (2018).' },
  '752': { name: 'Sweden', description: 'Stockholm (2018).' },
  '276': { name: 'Germany', description: 'Warnemünde & Berlin (2018).' },
  '208': { name: 'Denmark', description: 'Copenhagen (2018).' },
  '348': { name: 'Hungary', description: 'Budapest (2018).' },
  '620': { name: 'Portugal', description: 'Porto, Lisbon & Albufeira (2018).' },
  '392': { name: 'Japan', description: 'Tokyo, bullet train to Hakone & Mt. Fuji (2019).' },
  '144': { name: 'Sri Lanka', description: 'Colombo (2019).' },
  '356': { name: 'India', description: 'Cochin, Mumbai & Goa (2019).' },
  '32':  { name: 'Argentina', description: 'Salta, Cachi, Purmamarca, Cafayete & Iguazú (2022/23). Biked from Argentina into Brazil at Iguazú Falls.' },
  '76':  { name: 'Brazil', description: 'Iguazú Falls (2022/23). Rio de Janeiro for work (2025).' },
  '56':  { name: 'Belgium', description: 'F1 Grand Prix — country #46 (2023).' },
  '442': { name: 'Luxembourg', description: 'Country #47 (2023).' },
}
